const ROSBRIDGE_PORT = 9090;
const FOXGLOVE_PORT = 8765;
const UBUNTU_IP = "100.68.218.48";
const UBUNTU_WS_URL = `ws://${UBUNTU_IP}:${ROSBRIDGE_PORT}`;
const FOXGLOVE_URL = `ws://${UBUNTU_IP}:${FOXGLOVE_PORT}`;

export const ROS_CONFIG = {
  ROSBRIDGE: ROSBRIDGE_PORT,
  UBUNTU_IP,
  UBUNTU_WS_URL,
  FOXGLOVE_URL,
  RECONNECT_INTERVAL: 3000,
};
